### PR TITLE
Added RTIC-based RP2040 event-driven example.

### PR DESCRIPTION
**Pull request by riskable**
This adds a (working) example of how to use `infrared` with the rp2040 using RTIC.

### CODE REVIEW

**Comment by riskable** [comment]
Yes: Even though I created this example to demonstrate how `infrared` _wasn't_ working this "minimum example code" actually works fine, LOL.

**Comment by jkristell** [comment]
Thanks!

I ordered a Pico yesterday with the intent to make it my rp2040 test board for Infrared. As soon as the fugit branch is merged I will merge this as well.

**Comment by jkristell** [comment]
I merge the tempus-fugit branch to master and is about the release 0.14. Could you rebase your examples on master?

**Comment by riskable** [comment]
@jkristell Nooo problem!  Submitted PR #85

(I even tested that it works as expected with your latest code from master 👍)

**Pull request closed without merging**
